apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pfm
  name: pfm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pfm
  strategy: {}
  template:
    metadata:
      labels:
        app: pfm
    spec:
      containers:
      - image: pahlevani/pfm:v0.0.3-alpha
        name: pfm
        env:
        - name: SECURITY_OAUTH2_JWT_ISSUER_URI
          value: "https://accounts.google.com"
        - name: SWAGGER_OAUTH_AUDIENCE
          valueFrom:
            secretKeyRef:
              name: pfm-secrets
              key: oauth-client-id
        - name: SWAGGER_OAUTH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: pfm-secrets
              key: oauth-client-id
        - name: SWAGGER_OAUTH_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: pfm-secrets
              key: oauth-client-secret
        - name: JDBC_URL
          valueFrom:
            secretKeyRef:
              name: pfm-postgres-app
              key: jdbc-uri
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: pfm-postgres-app
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pfm-postgres-app
              key: password
        resources: {}
