apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  labels:
    app: pfm
  name: pfm-postgres
spec:
  instances: 1
  storage:
    size: 1Gi
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: pfm
    release: kube-prom-stack
  name: pfm-postgres-monitor
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": pfm-postgres
  podMetricsEndpoints:
  - port: metrics
