apiVersion: v1
kind: Service
metadata:
  labels:
    app: pfm
  name: pfm
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: pfm
  type: ClusterIP
